In [ ]:
!pip install git+https://github.com/sithmi4/Statistical-Learning-e23207.git

Collecting git+https://github.com/sithmi4/Statistical-Learning-e23207.git
  Cloning https://github.com/sithmi4/Statistical-Learning-e23207.git to /tmp/pip-req-build-4n7qm5p8
  Running command git clone --filter=blob:none --quiet https://github.com/sithmi4/Statistical-Learning-e23207.git /tmp/pip-req-build-4n7qm5p8
  Resolved https://github.com/sithmi4/Statistical-Learning-e23207.git to commit 25136ea64158fe8b0c9ef4d8ddb41409b2e11c64
  Preparing metadata (setup.py) ... done
Requirement already satisfied: pandas>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from data_inspector==0.1.0) (2.2.2)
Requirement already satisfied: numpy>=1.23.0 in /usr/local/lib/python3.12/dist-packages (from data_inspector==0.1.0) (2.0.2)
Requirement already satisfied: plotly>=5.10.0 in /usr/local/lib/python3.12/dist-packages (from data_inspector==0.1.0) (5.24.1)
Requirement already satisfied: scipy>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from data_inspector==0.1.0) (1.16.3)
Requirement already satisfied: statsmodels>=0.13.0 in /usr/local/lib/python3.12/dist-packages (from data_inspector==0.1.0) (0.14.6)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.5.0->data_inspector==0.1.0) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.5.0->data_inspector==0.1.0) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.5.0->data_inspector==0.1.0) (2026.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly>=5.10.0->data_inspector==0.1.0) (9.1.4)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from plotly>=5.10.0->data_inspector==0.1.0) (26.2)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.12/dist-packages (from statsmodels>=0.13.0->data_inspector==0.1.0) (1.0.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.5.0->data_inspector==0.1.0) (1.17.0)
Building wheels for collected packages: data_inspector
  Building wheel for data_inspector (setup.py) ... done
  Created wheel for data_inspector: filename=data_inspector-0.1.0-py3-none-any.whl size=6615 sha256=231967ae14598ff751c097973e57be0bb4a7fa6fe51f14b60002d5e2820c140a
  Stored in directory: /tmp/pip-ephem-wheel-cache-7xjap62e/wheels/c5/bb/85/d2d8ca1e544143bc3d9011cb59c53edcde3f2f79a31a784cad
Successfully built data_inspector
Installing collected packages: data_inspector
Successfully installed data_inspector-0.1.0

In [ ]:
from data_inspector import DataInspector

# Initialize your tool
inspector = DataInspector()

# Trigger the upload portal
inspector.upload_data()

Saving titanic_sample.csv to titanic_sample.csv
✅ Successfully loaded 'titanic_sample.csv' (20 rows, 10 columns).

In [ ]:
inspector.data_summary()

============================================================
 STRUCTURAL SUMMARY: 20 Rows | 10 Columns
 Numeric Features (7): ['PassengerId', 'Survived', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare']
 Categorical Features (3): ['Name', 'Sex', 'Embarked']
============================================================

📊 FIRST 20 ROWS PREVIEW:

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley",female,38.0,1,0,512.3292,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath",female,35.0,1,0,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,8.0500,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,8.4583,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,51.8625,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,21.0750,S
8,9,1,3,"Johnson, Mrs. Oscar W",female,27.0,0,2,11.1333,S
9,10,1,2,"Nasser, Mrs. Nicholas",female,14.0,1,0,30.0708,C
10,11,1,3,"Sandstrom, Miss. Marguerite",female,4.0,1,1,16.7000,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,26.5500,S
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,8.0500,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,31.2750,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda",female,14.0,0,0,7.8542,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,16.0000,S
16,17,0,3,"Rice, Master. Eugene",male,2.0,4,1,29.1250,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,13.0000,S
18,19,0,3,"Vander Planke, Mrs. Julius",female,31.0,1,0,18.0000,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,7.2250,C

In [ ]:
inspector.data_summary()

============================================================
 STRUCTURAL SUMMARY: 20 Rows | 10 Columns
 Numeric Features (7): ['PassengerId', 'Survived', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare']
 Categorical Features (3): ['Name', 'Sex', 'Embarked']
============================================================

📊 FIRST 20 ROWS PREVIEW:

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley",female,38.0,1,0,512.3292,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath",female,35.0,1,0,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,8.0500,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,8.4583,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,51.8625,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,21.0750,S
8,9,1,3,"Johnson, Mrs. Oscar W",female,27.0,0,2,11.1333,S
9,10,1,2,"Nasser, Mrs. Nicholas",female,14.0,1,0,30.0708,C
10,11,1,3,"Sandstrom, Miss. Marguerite",female,4.0,1,1,16.7000,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,26.5500,S
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,8.0500,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,31.2750,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda",female,14.0,0,0,7.8542,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,16.0000,S
16,17,0,3,"Rice, Master. Eugene",male,2.0,4,1,29.1250,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,13.0000,S
18,19,0,3,"Vander Planke, Mrs. Julius",female,31.0,1,0,18.0000,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,7.2250,C

In [ ]:
inspector.handle_missing_values(strategy='median')

✅ Missing value resolution achieved via strategy: 'median'.

In [ ]:
inspector.handle_outliers(columns=['Fare'], action='flag')
inspector.data_summary()

🚩 Outliers flagged successfully in the 'is_outlier' column.
============================================================
 STRUCTURAL SUMMARY: 20 Rows | 11 Columns
 Numeric Features (8): ['PassengerId', 'Survived', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare', 'is_outlier']
 Categorical Features (3): ['Name', 'Sex', 'Embarked']
============================================================

📊 FIRST 20 ROWS PREVIEW:

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Fare,Embarked,is_outlier
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,7.2500,S,0
1,2,1,1,"Cumings, Mrs. John Bradley",female,38.0,1,0,512.3292,C,1
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,7.9250,S,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath",female,35.0,1,0,53.1000,S,0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,8.0500,S,0
5,6,0,3,"Moran, Mr. James",male,27.0,0,0,8.4583,Q,0
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,51.8625,S,0
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,21.0750,S,0
8,9,1,3,"Johnson, Mrs. Oscar W",female,27.0,0,2,11.1333,S,0
9,10,1,2,"Nasser, Mrs. Nicholas",female,14.0,1,0,30.0708,C,0
10,11,1,3,"Sandstrom, Miss. Marguerite",female,4.0,1,1,16.7000,S,0
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,26.5500,S,0
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,8.0500,S,0
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,31.2750,S,0
14,15,0,3,"Vestrom, Miss. Hulda Amanda",female,14.0,0,0,7.8542,S,0
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,16.0000,S,0
16,17,0,3,"Rice, Master. Eugene",male,2.0,4,1,29.1250,Q,0
17,18,1,2,"Williams, Mr. Charles Eugene",male,27.0,0,0,13.0000,S,0
18,19,0,3,"Vander Planke, Mrs. Julius",female,31.0,1,0,18.0000,S,0
19,20,1,3,"Masselmani, Mrs. Fatima",female,27.0,0,0,7.2250,C,0

In [ ]:
inspector.plot_all_associations_heatmap()

In [ ]:
# To normalize your numerical columns (e.g., Age and Fare):
scaled_numeric = inspector.extract_normalized_numeric_data(columns=['age', 'fare'], strategy='standard')

# To preview the scaled output matrix:
scaled_numeric.head()

   age_standard  fare_standard
0     -0.565736      -0.502445
1      0.663861       0.786845
2     -0.258337      -0.488854
3      0.433312       0.420730
4      0.433312      -0.486337

In [ ]:
# To plot categorical frequencies with raw counts and percentage labels:
fig_bar = PlottingMethods.plot_bar(inspector.df, 'embark_town')
fig_bar.show()

# To verify your modular HTML embedding component generates correctly:
html_pie_component = PlottingMethods.plot_pie(inspector.df, column='who', title="Passenger Segment Breakdown", return_html=True)
print(f"HTML Component generated successfully! String length: {len(html_pie_component)} characters.")

HTML Component generated successfully! String length: 8230 characters.

In [ ]:
# A. Categorical vs Numeric (Generates a box plot with all data points)
inspector.plot_relationship('class', 'fare')

# B. Numeric vs Numeric (Generates a scatter plot with an OLS trendline)
inspector.plot_relationship('age', 'fare')

# C. Categorical vs Categorical (Generates a grouped bar chart)
inspector.plot_relationship('sex', 'alive')

In [ ]:
# To plot the 3-panel univariate diagnostic array for the Age column:
inspector.plot_univariate_subplots('age')